// <auto-generated />
namespace ShiftRight.Heim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Added_FloorVariant_Name_And_Removed_FloorNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_FloorVariant_Name_And_Removed_FloorNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201311131014131_Added_FloorVariant_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
