// <auto-generated />
namespace ShiftRight.Heim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Renamed_DTA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renamed_DTA));
        
        string IMigrationMetadata.Id
        {
            get { return "201311111002422_Renamed_DTA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
